Create ru_ru.lang
the-realest-stu/DynamicTrees-BOP pull request #43
Opened 2019-03-15 16:44 UTC by SSKirillSS

2019-03-16 18:23 UTC, SkyHawkB commented
I'll check it over and edit this if I have any suggestions.

2019-03-17 23:30 UTC, kierajreed requested changes

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +item.dynamictreesbop:magicseed.name=Магическое семя
`волшебное` is a better adjective to use here.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +item.dynamictreesbop:oakdyingseed.name=Мертвый жёлудь
Since it is "dying", not "dead", `умирающей` could work better.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +item.dynamictreesbop:mangroveseed.name=Мaнгровое семя
See previous comment.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +item.dynamictreesbop:whitecherryseed.name=Косточка белый сакуры
`вишня` is better than `сакура`.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +item.dynamictreesbop:redwoodseed.name=Шишка красного дерева
`секвойя` sounds more natural than literal "red wood".

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +item.dynamictreesbop:mahoganyseed.name=Стручок махагони
Consider switching the possessive to an adjective.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +tile.dynamictreesbop:leaves7.name=Листва
Use `листя` instead.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +tile.dynamictreesbop:leaves_palm.name=Пальмовая листва
See above. Also change the adjective to agree with the plural.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +tile.dynamictreesbop:magicbranch.name=Ствол магического дерева
Use `волшебное`.

2019-03-17 23:30 UTC, SkyHawkB commented on src/main/resources/assets/dynamictreesbop/lang/ru_ru.lang
> +tile.dynamictreesbop:bamboobranch.name=Ствол бамбукового дерева
Remove all the `дерева` and try to use the tree's actual names.

2022-01-20 20:05 UTC, closed without merging